# ansible remote user account
# ansible_ssh_user: centos

# ansible groups for service configuration
etcd_group_name: role=control
master_group_name: role=control
minion_group_name: role=worker

# Users to create for basic auth in Kubernetes API via HTTP
kube_users:
  kube:
    pass: changeme
    role: admin
  root:
    pass: changeme
    role: admin

# Kubernetes cluster name, also will be used as DNS domain
cluster_name: cluster.local

# Kubernetes internal network for services, unused block of space.
kube_service_addresses: 10.254.0.0/16

# Flannel internal network (optional). When flannel is used, it will assign IP
# addresses from this range to individual pods.
# This network must be unused in your network infrastructure!
kube_overlay_network: 4.0.0.0/16

# Internal DNS configuration.
# Kubernetes can create and mainatain its own DNS server to resolve service names
# into appropriate IP addresses. It's highly advisable to run such DNS server,
# as it greatly simplifies configuration of your applications - you can use
# service names instead of magic environment variables.
# You still must manually configure all your containers to use this DNS server,
# Kubernetes won't do this for you (yet).

# Turn this varable to 'false' to disable whole DNS configuration.
dns_setup: true

# Number of replicas of DNS instances started on kubernetes
dns_replicas: 1
