---
- name: RabbitMQ | Write pod file
  sudo: yes
  copy:
    src: rabbitmq-rc.yaml
    dest: "{{ kube_manifest_dir }}/rabbitmq-rc.yaml"
  register: rabbitmq_rc_def
  when: enable_metrics
  tags:
    - sensu-server
    - rabbitmq

- name: RabbitMQ | Write service file
  sudo: yes
  copy:
    src: rabbitmq-svc.yaml
    dest: "{{ kube_manifest_dir }}/rabbitmq-svc.yaml"
  register: rabbitmq_svc_def
  when: enable_metrics
  tags:
    - sensu-server
    - rabbitmq

- name: RabbitMQ | Create or update replication controller
  sudo: yes
  kube:
    namespace: kube-system
    resource: rc
    name: rabbitmq-master-v1
    filename: "{{ kube_manifest_dir }}/rabbitmq-rc.yaml"
    state: "{{ rabbitmq_rc_def.changed | ternary('latest','present') }}"
  when: enable_metrics
  tags:
    - sensu-server
    - rabbitmq

- name: RabbitMQ | Create or update service
  sudo: yes
  kube:
    namespace: kube-system
    resource: svc
    name: rabbitmq-master
    filename: "{{ kube_manifest_dir }}/rabbitmq-svc.yaml"
    state: "{{ rabbitmq_svc_def.changed | ternary('latest','present') }}"
  when: enable_metrics
  tags:
    - sensu-server
    - rabbitmq
