---
- hosts: all
  sudo: yes
  roles:
          - common

- hosts: role=control
  sudo: yes
  roles:
          - etcd
          - flannel-config
          - flannel
          - kubernetes
          - master
          - skydns

- hosts: role=worker
  sudo: yes
  roles:
          - flannel
          - docker
          - kubernetes
          - minion
