---
# all facts for all hosts are gathered; and the common packages
# and configurations are performed on each host.
- hosts: all
  roles:
    - common
    - secrets

# provide the control plane
- hosts: role=master
  gather_facts: no
  roles:
    - etcd
    - flannel
    - master
    - addons
    - dnsmasq

# provide the execution plane
- hosts: role=node
  gather_facts: no
  roles:
    - docker
    - flannel
    - minion
    - dnsmasq
