---
- hosts: all
  roles:
    - common

- hosts: role=control
  gather_facts: no
  roles:
    - etcd
    - master
    - skydns

- hosts: role=worker
  gather_facts: no
  roles:
    - docker
    - flannel
    - minion
