---
# all facts for all hosts are gathered; and the common packages
# and configurations are performed on each host.
- name: All
  hosts: all
  roles:
    - common
    - secrets

# provide the control plane
- name: Master
  hosts: master
  gather_facts: no
  roles:
    - etcd
    - flannel
    - kubernetes
    - master
    - addons
    - dnsmasq

# provide the execution plane
- name: Node
  hosts: node
  gather_facts: no
  roles:
    - etcd
    - docker
    - flannel
    - kubernetes
    - minion
    - dnsmasq
