---
- name: Sensu Client | Create pod
  sudo: yes
  template:
    src: sensu-client.yaml.j2
    dest: "{{ kube_manifest_dir }}/sensu-client.yaml"
  register: sensu_client_def
  when: enable_metrics
  tags:
    - sensu-client
