---
- name: restart flannel
  sudo: yes
  service:
    name: flanneld
    state: restarted
  notify:
    - stop docker
    - delete docker0
    - start docker

- name: stop docker
  sudo: yes
  service:
    name: docker
    state: stopped

- name: delete docker0
  sudo: yes
  command: ip link delete docker0
  ignore_errors: yes

- name: start docker
  sudo: yes
  service:
    name: docker
    state: started
