---
- name: reload systemd
  sudo: yes
  shell: systemctl daemon-reload
  when: etcd_peers.changed

- name: restart etcd
  sudo: yes
  service:
    name: etcd
    state: restarted
  when: etcd_peers.changed

- name: restart iptables
  sudo: yes
  service:
    name: iptables
    state: restarted
