apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: gcr.io/google_containers/hyperkube:{{ kube_version }}
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    - --etcd-servers={% for node in groups['master'] %}{{ etcd_url_scheme }}://{{ node }}:{{ etcd_client_port }}{% if not loop.last %},{% endif %}{% endfor %}

    - --allow-privileged=true
    - --service-cluster-ip-range={{ kube_service_addresses }}
    - --secure_port={{ kube_master_port }}
    - --advertise-address={{ ansible_default_ipv4.address }}
    - --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
    - --tls-cert-file={{ kube_cert_dir }}/server.crt
    - --tls-private-key-file={{ kube_cert_dir }}/server.key
    - --client-ca-file={{ kube_cert_dir }}/ca.crt
    - --service-account-key-file={{ kube_cert_dir }}/server.key
    - --basic-auth-file={{ kube_users_dir }}/known_users.csv
    - --runtime-config=extensions/v1beta1/daemonsets=true
    - --v={{kube_log_level}}
    ports:
    - containerPort: 443
      hostPort: 443
      protocol: TCP
      name: https
    - containerPort: 8080
      hostPort: 8080
      protocol: TCP
      name: local
    volumeMounts:
    - mountPath: {{ kube_config_dir }}
      name: etc-kubernetes
      readOnly: true
  volumes:
  - hostPath:
      path: {{ kube_config_dir }}
    name: etc-kubernetes
