apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: gcr.io/google_containers/hyperkube:{{ kube_version }}
    command:
    - /hyperkube
    - controller-manager
    - --master=http://127.0.0.1:8080
    - --service-account-private-key-file={{ kube_cert_dir }}/server.key
    - --root-ca-file={{ kube_cert_dir }}/ca.crt
    - --cloud-provider={{ cloud_provider if enable_cloud_provider else "" }}
    - --cloud-config={{ cloud_provider_config if enable_cloud_provider else "" }}
    - --v={{kube_log_level}}
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 1
    volumeMounts:
    - mountPath: {{ kube_config_dir }}
      name: etc-kubernetes
      readOnly: true
  volumes:
  - hostPath:
      path: {{ kube_config_dir }}
    name: etc-kubernetes
