---
- name: Install etcd package
  sudo: yes
  yum:
    pkg: etcd
    state: latest
  notify:
    - restart etcd
  tags:
    - etcd

- name: Generated etcd config file
  sudo: yes
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
  notify:
    - restart etcd
  tags:
    - etcd

- name: Enable etcd service
  sudo: yes
  service:
     name: etcd
     enabled: yes
  tags:
    - etcd

- name: Start etcd service
  sudo: yes
  service:
     name: etcd
     state: started
  register: etcd_started
  tags:
    - etcd

