---
- name: Install etcd
  yum: pkg=etcd state=latest
  notify:
        - restart etcd

- name: Determine if etcd-0.4 or newer
  command: rpm -q etcd
  register: etcd_ver
  changed_when: false

- name: Write etcd config file for version 0.4.x
  template: src=etcd.04.conf.j2 dest=/etc/etcd/etcd.conf
  when: "'etcd-0.4' in etcd_ver.stdout"
  notify:
        - restart etcd

- name: Write etcd config file for version 2.0.x
  template: src=etcd.20.conf.j2 dest=/etc/etcd/etcd.conf
  when: "'etcd-2.0' in etcd_ver.stdout"
  notify:
        - restart etcd

- name: Enable etcd
  service: name=etcd enabled=yes state=started

- include: iptables.yml
