---
- name: Install etcd package
  sudo: yes
  yum:
    pkg: "etcd-{{ ectd_version }}.el7.x86_64.rpm"
    state: present
  when: inventory_hostname in groups[etcd_group_name]
  notify:
    - restart etcd
  tags:
    - etcd

- name: Write etcd config file
  sudo: yes
  template:
    src: etcd.conf.j2
    dest: "{{ etcd_conf_dir }}/etcd.conf"
  when: inventory_hostname in groups[etcd_group_name]
  notify:
    - restart etcd
  tags:
    - etcd

- name: Enable etcd service
  sudo: yes
  service:
     name: etcd
     enabled: yes
  when: inventory_hostname in groups[etcd_group_name]
  tags:
    - etcd

- name: Start etcd service
  sudo: yes
  service:
     name: etcd
     state: started
  when: inventory_hostname in groups[etcd_group_name]
  register: etcd_started
  tags:
    - etcd
