---
- name: create kubernetes config directories
  sudo: yes
  file: path={{ item }} state=directory
  with_items:
    - "{{ kube_config_dir }}"
    - "{{ kube_script_dir }}"
    - "{{ kube_manifest_dir }}"
    - "{{ kube_podmaster_dir }}"
    - "{{ kube_cert_dir }}"
    - "{{ kube_users_dir }}"
  tags:
    - kubernetes

- name: pull hyperkube docker image
  sudo: yes
  command: "docker pull gcr.io/google_containers/hyperkube:{{ kube_version }}"
  register: docker_pull_result
  changed_when: docker_pull_result.stdout.find('newer') > -1
  tags:
    - kubernetes

- include: secrets.yml
  tags:
    - secrets
