---
- name: Create kubernetes config directory
  sudo: yes
  file: path=/etc/kubernetes state=directory

- name: write the global config file
  sudo: yes
  template:
    src: config.j2
    dest: /etc/kubernetes/config
  notify:
    - restart daemons
  tags:
    - kubernetes
