---
- name: Get iptables rules
  shell: iptables -L
  register: iptablesrules
  always_run: yes

- name: Enable iptables at boot
  service: name=iptables enabled=yes state=started

- name: Open flannel vxlan port with iptables
  command: /sbin/iptables -I INPUT 1 -p udp --dport 8472 -j ACCEPT -m comment --comment "flannel_vxlan"
  when: iptablesrules.stdout.find("flannel_vxlan") == -1
  notify:
          - restart iptables

- name: Save iptables rules
  command: service iptables save
  when: iptablesrules.stdout.find("flannel_vxlan") == -1
