---
- name: get iptables rules
  shell: iptables -L -t nat
  register: iptablesrules
  always_run: yes
  changed_when: false
  tags:
    - flannel

- name: enable kernel packet forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes
  tags:
    - flannel

- name: enable flannel network masquarading
  command: /sbin/iptables -t nat -A POSTROUTING -s {{ kube_overlay_network }} -j MASQUERADE -m comment --comment "flannel_nat"
  when: iptablesrules.stdout.find("flannel_nat") == -1
  tags:
    - flannel
