---
- name: create flannel config json
  sudo: yes
  template:
    src: flannel.json.j2
    dest: /tmp/flannel.json
  tags:
    - flannel

- name: configure flannel in etcd
  run_once: true
  sudo: yes
  command: 'curl -L http://{{ groups[etcd_group_name][0] }}:4001/v2/keys/coreos.com/network/config -XPUT --data-urlencode value@/tmp/flannel.json'
  changed_when: false
  tags:
    - flannel

- name: delete flannel config json
  sudo: yes
  file:
    name: /tmp/flannel.json
    state: absent
  tags:
    - flannel

- name: install flannel
  sudo: yes
  yum:
    pkg=flannel
    state=latest
    enablerepo=virt7-docker-common-candidate
  tags:
    - flannel

- name: install flannel sysconfig file
  sudo: yes
  template:
    src: flanneld.j2
    dest: /etc/sysconfig/flanneld
  notify:
    - restart flannel
  tags:
    - flannel

- name: launch flannel
  sudo: yes
  service:
    name: flanneld
    state: started
    enabled: yes
  notify:
    - stop docker
    - delete docker0
    - start docker
  tags:
    - flannel

- include: iptables.yml
