---
# default is etc/utc in build 20141129 [http://cloud.centos.org/centos/7/images/]
- name: set timezone to etc/utc
  sudo: yes
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    state: link
    force: yes
  tags:
    - common

- name: check if selinux enforcing
  sudo: yes
  command: getenforce
  register: selinux
  changed_when: false
  tags:
    - common

- name: set selinux to permissive
  sudo: yes
  selinux: state=permissive policy=targeted
  when: "'Enforcing' in selinux.stdout"
  tags:
    - common

- name: disable firewalld
  sudo: yes
  service:
    name: firewalld
    enabled: false
    state: stopped
  when: ansible_distribution == "CentOS" and ansible_distribution_version == "7.1.1503"
  tags:
    - common

# add hosts to /etc/hosts
- name: populate inventory into hosts file
  sudo: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}$"
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
    state: present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all']
  tags:
    - common

- name: enable EPEL repo
  sudo: yes
  yum:
    name: epel-release
    state: latest
  tags:
    - common

- name: install docker-common-candidate repo
  sudo: yes
  copy:
    src=virt7-docker-common-candidate.repo
    dest=/etc/yum.repos.d/virt7-docker-common-candidate.repo
