---
# default is etc/utc in build 20141129 [http://cloud.centos.org/centos/7/images/]
- name: set timezone to etc/utc
  sudo: yes
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    state: link
    force: yes

# add hosts to /etc/hosts
- name: configure hosts file
  sudo: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}{% if use_host_domain %} {{ item }}.{{ host_domain }}{% endif %}$"
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}{% if use_host_domain %} {{ item }}.{{ host_domain}}{% endif %}"
    state: present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all']

- name: enable EPEL repo
  sudo: yes
  yum:
    name: epel-release
    state: latest

- name: bootstrap virt7-testing repo
  copy: src=virt7-testing.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: Set IP address variables
  set_fact:
    master_ip_address: "{{ hostvars[groups[master_group_name][0]]['ansible_default_ipv4']['address'] }}"
    etcd_ip_address: "{{ hostvars[groups[master_group_name][0]]['ansible_default_ipv4']['address'] }}"
