---
# default is etc/utc in build 20141129 [http://cloud.centos.org/centos/7/images/]
- name: set timezone to etc/utc
  sudo: yes
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    state: link
    force: yes
  tags:
    - common

# disable firewalld and iptables
- name: disable firewalld and iptables
  sudo: yes
  service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items:
    - firewalld
    - iptables-services
  when: ansible_distribution == "CentOS" and ansible_distribution_version == "7.1.1503"
  tags:
    - common

- name: check if selinux enforcing
  sudo: yes
  command: getenforce
  register: selinux
  changed_when: false
  tags:
    - common

- name: set selinux permissive
  sudo: yes
  selinux: state=permissive policy=targeted
  when: "'Enforcing' in selinux.stdout"
  tags:
    - common

# add hosts to /etc/hosts
- name: populate inventory into hosts file
  sudo: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}$"
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
    state: present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all']
  tags:
    - common

- name: clean hosts file
  sudo: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ item }}"
    state: absent
  with_items:
    - '^127\.0\.0\.1(\s+){{ inventory_hostname }}.*'
    - '^::1(\s+){{ inventory_hostname }}.*'
  tags:
    - common

- name: upgrade all packages
  sudo: yes
  yum: name=* state=latest
  tags:
    - common

- name: enable EPEL repo
  sudo: yes
  yum:
    name: epel-release
    state: latest
  tags:
    - common

- name: install docker-common-candidate repo
  sudo: yes
  copy:
    src=virt7-docker-common-candidate.repo
    dest=/etc/yum.repos.d/virt7-docker-common-candidate.repo
  when: package_channel == "testing"
  tags:
    - common

- name: evaluate first_master
  add_host:
    name: "{{ groups['master'][0] }}"
    groups: first_master
    when: "master in groups and groups['master'] | length > 1"
  tags:
    - common
