apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kube-system
  labels:
    name: kafka
spec:
  ports:
  - port: 2181
    name: zookeeper
    protocol: TCP
  - port: 9092
    name: kafka
    protocol: TCP
  selector:
    name: kafka
