apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-v1
  namespace: kube-system
  labels:
    name: kafka
    version: v1
spec:
  replicas: 1
  selector:
    name: kafka
    version: v1
  template:
    metadata:
      labels:
        name: kafka
        version: v1
    spec:
      containers:
        - image: spotify/kafka
          name: kafka
          resources:
            limits:
              cpu: 100m
          env:
          - name: ADVERTISED_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
          - containerPort: 2181
            name: zookeeper
          - containerPort: 9092
            name: kafka
