apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master-v1
  namespace: kube-system
  labels:
    name: redis-master
    version: v1
spec:
  replicas: 1
  selector:
    name: redis-master
    version: v1
  template:
    metadata:
      labels:
        name: redis-master
        version: v1
    spec:
      containers:
      - name: redis-master
        image: kubernetes/redis:v1
        resources:
          limits:
            cpu: 100m
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /redis-master-data
      volumes:
      - name: data
        emptyDir: {}
