apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: kube-system
  labels:
    name: redis-master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-master
