---
- name: Get iptables rules
  shell: iptables -L
  register: iptablesrules
  always_run: yes

- name: Enable iptables at boot
  service: name=iptables enabled=yes state=started

- name: Open apiserver port with iptables
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8080 -j ACCEPT -m comment --comment "kube-apiserver"
  when: iptablesrules.stdout.find("kube-apiserver") == -1
  notify:
          - restart iptables

- name: Save iptables rules
  command: service iptables save
  when: iptablesrules.stdout.find("kube-apiserver") == -1
