---
- name: write the config files for api server
  template: src=apiserver.j2 dest=/etc/kubernetes/apiserver
  notify:
          - restart apiserver
          - restart controller-manager
          - restart scheduler

- name: write config file for controller-manager
  template: src=controller-manager.j2 dest=/etc/kubernetes/controller-manager
  notify:
          - restart controller-manager
  tags: load_nodes

- name: write the config file for scheduler
  copy: src=scheduler dest=/etc/kubernetes/scheduler
  notify:
          - restart scheduler

- name: create kubernetes env dir
  file: path=/var/run/kubernetes state=directory mode=0755 owner=kube group=kube
  sudo: yes

- name: Enable apiserver
  service: name=kube-apiserver enabled=yes state=started

- name: Enable controller-manager
  service: name=kube-controller-manager enabled=yes state=started

- name: Enable scheduler
  service: name=kube-scheduler enabled=yes state=started

- include: load_nodes.yml
  tags: load_nodes
