---
- name: Install kubernetes master
  sudo: yes
  yum:
    pkg=kubernetes-master
    state=latest
    enablerepo=virt7-docker-common-candidate
  notify:
    - restart daemons
  tags:
    - master

- name: write the config files for api server
  sudo: yes
  template:
    src: apiserver.j2
    dest: /etc/kubernetes/apiserver
  notify:
    - restart daemons
  tags:
    - master

- name: write config file for controller-manager
  sudo: yes
  template:
    src: controller-manager.j2
    dest: /etc/kubernetes/controller-manager
  notify:
    - restart controller-manager
  tags:
    - master

- name: write the config file for scheduler
  sudo: yes
  copy:
    src: scheduler
    dest: /etc/kubernetes/scheduler
  notify:
    - restart scheduler
  tags:
    - master

- name: create kubernetes env dir
  sudo: yes
  file:
    path: /var/run/kubernetes
    state: directory
    mode: 0755
    owner: kube
    group: kube
  tags:
    - master

- name: Enable apiserver
  sudo: yes
  service:
    name: kube-apiserver
    enabled: yes
    state: started
  tags:
    - master

- name: Enable controller-manager
  sudo: yes
  service:
    name: kube-controller-manager
    enabled: yes
    state: started
  tags:
    - master

- name: Enable scheduler
  sudo: yes
  service:
    name: kube-scheduler
    enabled: yes
    state: started
  tags:
    - master

- include: load_nodes.yml
