---
- include: secrets.yml
  tags:
    - secrets

- name: download kubernetes binaries
  sudo: yes
  get_url: url={{ kube_url }}/{{ item }} dest=/usr/bin mode=0753
  with_items:
    - kubelet
    - kubectl
  tags:
    - master

- name: generate kublet systemd unit
  sudo: yes
  template:
    src: kubelet.service.j2
    dest: /usr/lib/systemd/system/kubelet.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart kubelet
  tags:
    - master

- name: enable and start kubelet service
  sudo: yes
  service:
    name: kubelet
    enabled: yes
    state: started
  tags:
    - master

- name: generate kubernetes manifests
  sudo: yes
  template:
    src: "{{ item }}.yml"
    dest: "{{ kube_manifest_dir }}/{{ item }}.yml"
    owner: root
    group: root
    mode: 0644
  with_items:
    - kube-apiserver
    - kube-proxy
    - kube-podmaster
    - kube-system
  tags:
    - master

- name: generate kubernetes podmaster manifests
  sudo: yes
  template:
    src: "{{ item }}.yml"
    dest: "{{ kube_script_dir }}/manifests/{{ item }}.yml"
    owner: root
    group: root
    mode: 0644
  with_items:
    - kube-scheduler
    - kube-controller-manager
  tags:
    - master

- name: wait for apiserver is up
  wait_for: port=8080

- name: Create kube-system namespace
  sudo: yes
  kube:
    resource: namespace
    name: kube-system
    filename: "{{ kube_manifest_dir }}/kube-system.yml"
    state: present
  run_once: true
  tags:
    - master

- name: addons | logging | create fluentd pod
  sudo: yes
  copy:
    src: fluentd-es.yaml
    dest: "{{ kube_manifest_dir }}/fluentd-es.yaml"
  when: enable_logging
  tags:
    - addons
    - logging
