---
# - name: install latest device-mapper-libs
#   sudo: yes
#   yum:
#     name: device-mapper-libs
#     state: latest
#   tags:
#     - docker

- name: Install docker centos7 repo
  sudo: yes
  copy:
    src=docker.repo
    dest=/etc/yum.repos.d/docker.repo

- name: install docker
  sudo: yes
  yum:
    name: docker
    state: latest
    enablerepo: dockerrepo
  tags:
    - docker

- name: enable docker
  sudo: yes
  service:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker
