---
- name: install latest device-mapper-libs
  sudo: yes
  yum:
    name: device-mapper-libs
    state: latest

- name: install docker
  sudo: yes
  yum:
    name: docker
    state: latest
    enablerepo: virt7-testing

- name: enable docker
  sudo: yes
  service:
    name: docker
    enabled: yes
    state: started
