---
- name: install docker
  sudo: yes
  yum:
    name: "docker-{{ docker_version }}"
    state: present
  tags:
    - docker

- name: enable docker
  sudo: yes
  service:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker
