---
- name: Write kube-system namespace manifest
  sudo: yes
  copy:
    src=kube-system.yaml
    dest={{ kube_manifest_dir }}/kube-system.yaml

- name: Create kube-system namespace
  sudo: yes
  kube:
    resource: ns
    name: kube-system
    filename: "{{ kube_manifest_dir }}/kube-system.yaml"
    state: present
  tags:
    - addons

- name: Run kube-gen-token script to create {{ kube_token_dir }}/known_tokens.csv
  sudo: yes
  command: "{{ kube_script_dir }}/kube-gen-token.sh {{ item }}"
  environment:
    TOKEN_DIR: "{{ kube_token_dir }}"
  with_items:
    - "system:dns"
    - "system:monitoring"
    - "system:logging"
  register: gentoken
  changed_when: "'Added' in gentoken.stdout"
  notify:
    - restart apiserver
  tags:
    - addons

- include: skydns.yml
  when: dns_setup