---
- name: SkyDNS | Write pod file
  sudo: yes
  template:
    src: skydns-rc.yaml.j2
    dest: "{{ kube_manifest_dir }}/skydns-rc.yaml"
  register: dns_rc_def
  when: dns_setup
  tags:
    - addons

- name: SkyDNS | Write service file
  sudo: yes
  template:
    src: skydns-svc.yaml.j2
    dest: "{{ kube_manifest_dir }}/skydns-svc.yaml"
  register: dns_svc_def
  when: dns_setup
  tags:
    - addons

- name: SkyDNS | Create or update replication controller
  sudo: yes
  kube:
    namespace: kube-system
    resource: rc
    name: kube-dns-v8
    filename: "{{ kube_manifest_dir }}/skydns-rc.yaml"
    state: "{{ dns_rc_def.changed | ternary('latest','present') }}"
  when: dns_setup
  tags:
    - addons

- name: SkyDNS | Create or update service
  sudo: yes
  kube:
    namespace: kube-system
    resource: svc
    name: kube-dns
    filename: "{{ kube_manifest_dir }}/skydns-svc.yaml"
    state: "{{ dns_svc_def.changed | ternary('latest','present') }}"
  when: dns_setup
  tags:
    - addons