---
- name: Write SkyDNS pod file
  sudo: yes
  template:
    src: skydns-rc.yaml.j2
    dest: /etc/kubernetes/skydns-rc.yaml
  register: dns_rc_def
  when: dns_setup
  tags:
    - skydns

- name: Write SkyDNS service file
  sudo: yes
  template:
    src: skydns-svc.yaml.j2
    dest: /etc/kubernetes/skydns-svc.yaml
  register: dns_svc_def
  when: dns_setup
  tags:
    - skydns

- name: Create or update SkyDNS replication controller
  sudo: yes
  kube:
    namespace: kube-system
    resource: rc
    name: kube-dns-v8
    filename: /etc/kubernetes/skydns-rc.yaml
    state: "{{ dns_rc_def.changed | ternary('latest','present') }}"
  when: dns_setup
  tags:
    - skydns

- name: Create or update SkyDNS service
  sudo: yes
  kube:
    namespace: kube-system
    resource: svc
    name: kube-dns
    filename: /etc/kubernetes/skydns-svc.yaml
    state: "{{ dns_svc_def.changed | ternary('latest','present') }}"
  when: dns_setup
  tags:
    - skydns

