---
- name: Write SkyDNS pod file
  sudo: yes
  template:
    src: skydns-rc.yaml.j2
    dest: /etc/kubernetes/skydns-rc.yaml
  when: dns_setup
  tags:
    - skydns

- name: Write SkyDNS service file
  sudo: yes
  template:
    src: skydns-svc.yaml.j2
    dest: /etc/kubernetes/skydns-svc.yaml
  when: dns_setup
  tags:
    - skydns

- name: Check that the DNS RC exists
  sudo: yes
  shell: kubectl get rc kube-dns-v8 --namespace=kube-system
  register: has_dns_pod
  failed_when: false
  changed_when: false
  tags:
    - skydns

- name: Create SkyDNS pod
  sudo: yes
  shell: kubectl create -f /etc/kubernetes/skydns-rc.yaml
  when: dns_setup and has_dns_pod.rc != 0
  tags:
    - skydns

- name: Update DNS replication service
  sudo: yes
  shell: kubectl replace -f /etc/kubernetes/skydns-rc.yaml
  when: dns_setup and has_dns_pod.rc == 0
  tags:
    - skydns

- name: Check that the DNS service exists
  sudo: yes
  shell: kubectl get service kube-dns --namespace=kube-system
  register: has_dns_service
  failed_when: false
  changed_when: false
  tags:
    - skydns

- name: Create SkyDNS service
  sudo: yes
  shell: kubectl create -f /etc/kubernetes/skydns-svc.yaml
  when: dns_setup and has_dns_service.rc != 0
  tags:
    - skydns

- name: Update SkyDNS service
  sudo: yes
  shell: kubectl replace -f /etc/kubernetes/skydns-svc.yaml
  when: dns_setup and has_dns_service.rc == 0
  tags:
    - skydns
