---
- name: Write SkyDNS pod file
  template: src=skydns-rc.yaml.j2 dest=/etc/kubernetes/skydns-rc.yaml
  when: dns_setup

- name: Write SkyDNS service file
  template: src=skydns-svc.yaml.j2 dest=/etc/kubernetes/skydns-svc.yaml
  when: dns_setup


- name: Check that the DNS pod exists
  shell: kubectl get rc kube-dns
  register: has_dns_pod
  failed_when: false
  changed_when: false

- name: Create SkyDNS pod
  shell: kubectl create -f /etc/kubernetes/skydns-rc.yaml
  when: dns_setup and has_dns_pod.rc != 0

- name: Update DNS replication service
  shell: kubectl update -f /etc/kubernetes/skydns-rc.yaml
  when: dns_setup and has_dns_pod.rc == 0


- name: Check that the DNS service exists
  shell: kubectl get service kube-dns
  register: has_dns_service
  failed_when: false
  changed_when: false

- name: Create SkyDNS service
  shell: kubectl create -f /etc/kubernetes/skydns-svc.yaml
  when: dns_setup and has_dns_service.rc != 0

- name: Update SkyDNS service
  shell: kubectl update -f /etc/kubernetes/skydns-svc.yaml
  when: dns_setup and has_dns_service.rc == 0
