- hosts: all
  gather_facts: no
  tasks:
    - name: wait for ssh to become available
      local_action: wait_for
                    port=22
                    host="{{ ansible_ssh_host | default(inventory_hostname) }}"
                    search_regex=OpenSSH
                    delay=10
