---
- name: Install kubernetes node
  sudo: yes
  yum:
    pkg=kubernetes-node
    state=latest
    enablerepo=virt7-docker-common-candidate
  notify:
    - restart daemons
  tags:
    - minion

- name: Get the node token values
  sudo: yes
  slurp:
    src: "{{ kube_token_dir }}/{{ item }}-{{ inventory_hostname }}.token"
  with_items:
    - "system:kubelet"
    - "system:proxy"
  register: tokens
  run_once: true
  delegate_to: "{{ groups[master_group_name][0] }}"
  tags:
    - minion

- name: Set token facts
  set_fact:
    kubelet_token: "{{ tokens.results[0].content|b64decode }}"
    proxy_token: "{{ tokens.results[1].content|b64decode }}"
  tags:
    - minion

- name: write the config files for kubelet
  sudo: yes
  template: src=kubelet.j2 dest={{ kube_config_dir }}/kubelet
  notify:
    - restart kubelet
  tags:
    - minion

- name: write the kubecfg (auth) file for kubelet
  sudo: yes
  template: src=kubelet.kubeconfig.j2 dest={{ kube_config_dir }}/kubelet.kubeconfig
  notify:
    - restart kubelet
  tags:
    - minion

- name: write the config files for proxy
  sudo: yes
  template: src=proxy.j2 dest={{ kube_config_dir }}/proxy
  notify:
    - restart proxy
  tags:
    - minion

- name: write the kubecfg (auth) file for kube-proxy
  sudo: yes
  template: src=proxy.kubeconfig.j2 dest={{ kube_config_dir }}/proxy.kubeconfig
  notify:
    - restart proxy
  tags:
    - minion

- name: Enable kubelet
  sudo: yes
  service:
    name: kubelet
    enabled: yes
    state: started
  tags:
    - minion

- name: Enable proxy
  sudo: yes
  service:
    name: kube-proxy
    enabled: yes
    state: started
  tags:
    - minion
