---
- name: Check if selinux enforcing
  sudo: yes
  command: getenforce
  register: selinux
  changed_when: false
  tags:
    - minion

- name: Set selinux permissive because tokens and selinux don't work together
  sudo: yes
  selinux: state=permissive policy=targeted
  when: "'Enforcing' in selinux.stdout"
  tags:
    - minion

- include: stable.yml
  when: kube_build == "stable"

- include: testing.yml
  when: kube_build == "testing"

- include: secrets.yml

- name: write the config files for kubelet
  sudo: yes
  template: src=kubelet.j2 dest={{ kube_config_dir }}/kubelet
  notify:
    - restart kubelet
  tags:
    - minion

- name: write the kubecfg (auth) file for kubelet
  sudo: yes
  template: src=kubelet.kubeconfig.j2 dest={{ kube_config_dir }}/kubelet.kubeconfig
  notify:
    - restart kubelet
  tags:
    - minion

- name: write the config files for proxy
  sudo: yes
  template: src=proxy.j2 dest={{ kube_config_dir }}/proxy
  notify:
    - restart proxy
  tags:
    - minion

- name: write the kubecfg (auth) file for kube-proxy
  sudo: yes
  template: src=proxy.kubeconfig.j2 dest={{ kube_config_dir }}/proxy.kubeconfig
  notify:
    - restart proxy
  tags:
    - minion

- name: Enable kubelet
  sudo: yes
  service:
    name: kubelet
    enabled: yes
    state: started
  tags:
    - minion

- name: Enable proxy
  sudo: yes
  service:
    name: kube-proxy
    enabled: yes
    state: started
  tags:
    - minion

- name: addons | Logging | Create Fluentd pod
  sudo: yes
  copy:
    src: fluentd-es.yaml
    dest: "{{ kube_manifest_dir }}/fluentd-es.yaml"
  when: enable_logging
  tags:
    - addons
    - logging
