---
- name: certs | upload certificates to nodes
  sudo: yes
  copy:
    src="{{ cert_syncdir.path }}/certs/{{ item }}"
    dest="{{ kube_cert_dir }}/{{ item }}"
    group="{{ kube_cert_group }}"
    mode=0440
  with_items:
    - "ca.crt"
    - "kubelet.crt"
    - "kubelet.key"
  # notify:
  #   - restart daemons
